### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by msarmi9** [msarmi9/Sparkle#154]
**Task:** Now that our project is approach it's first initial release (v1.0 🙌), we should make sure our documentation is in good order. This includes

* [ ] Updating our introduction.
* [ ] Updating the tutorial section. This should include different ways to run our project locally, e.g. by via `git clone` and `docker.
* [ ] Adding other pages as needed.
