### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by msarmi9** [msarmi9/Sparkle#155]
**Task:** Quite a few things have changed since we last updated our README. We should include

* [x] An embedded YoutTube link to our video pitch at the top.
* [ ] A mission statement.
* [ ] A brief overview of the three components of our project.
* [ ] Detailed instructions on how to reproduce our work.
